version: "3"

services:

  freeswitch:
    container_name: "freeswitch"
    build:
      context: .
      args:
        - SIGNALWIRE_TOKEN=${SIGNALWIRE_TOKEN}
    volumes:
      - ./conf:/etc/freeswitch
    stdin_open: true
    tty: true
    env_file: .env
    network_mode: "host"
